# <VirtualHost *:80>
#   ServerName smartnet.nighttime.online
#   Redirect permanent / https://smartnet.nighttime.online/
# </VirtualHost>

# <VirtualHost *:443>
#   ServerName smartnet.nighttime.online

#   DocumentRoot /var/www/smartnet/frontend/dist

#   SSLEngine on
#   SSLCertificateFile /etc/letsencrypt/live/smartnet.nighttime.online/fullchain.pem
#   SSLCertificateKeyFile /etc/letsencrypt/live/smartnet.nighttime.online/privkey.pem

#   <Directory /var/www/smartnet/frontend/dist>
#     Options -Indexes +FollowSymLinks
#     AllowOverride All
#     Require all granted
#   </Directory>

#   ProxyPreserveHost On
#   ProxyPass /api http://localhost:5000/api
#   ProxyPassReverse /api http://localhost:5000/api

#   <Location /api>
#     ProxyPreserveHost On
#     ProxyPass http://localhost:5000/api
#     ProxyPassReverse http://localhost:5000/api
#   </Location>

#   ErrorLog ${APACHE_LOG_DIR}/smartnet-error.log
#   CustomLog ${APACHE_LOG_DIR}/smartnet-access.log combined


<VirtualHost *:80>
    ServerName smartnet.nighttime.online

    DocumentRoot /var/www/smartnet/frontend/dist

    <Directory /var/www/smartnet/frontend/dist>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ProxyPreserveHost On
    ProxyPass /api http://localhost:5000/api
    ProxyPassReverse /api http://localhost:5000/api

    ErrorLog ${APACHE_LOG_DIR}/smartnet-error.log
    CustomLog ${APACHE_LOG_DIR}/smartnet-access.log combined
</VirtualHost>